# Automated Deployment to cPanel via FTP (GitHub Actions)
name: Deploy to cPanel

on:
  push:
    branches: [ "main" ]

jobs:
  web-deploy:
    name: Deploy to cPanel Web Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v4

      - name: Sync files to cPanel FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER != '' && secrets.CPANEL_FTP_SERVER || '51.195.60.233' }}
          username: ${{ secrets.CPANEL_FTP_USERNAME != '' && secrets.CPANEL_FTP_USERNAME || 'sahashra' }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          port: 21
          server-dir: /public_html/
